import 'app/globals.css'

export const dynamic = 'force-dynamic'

export const metadata = {
  title: '物販',
  description: 'Generated by create next app',
}

export default function NailRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
