import 'app/globals.css'

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'カラーページ',
  description: 'Generated by create next app',
}

export default function NailRootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  )
}
